services:
  postgres:
    image: postgres:16-alpine
    container_name: amazing-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amazing_db
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d amazing_db"]
      interval: 5s
      timeout: 5s
      retries: 5
